process.on('uncaughtException', (error) => {
  throw error;
});
